version: "2"
services:
  jupyterhub:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: jupyterhub
    ports:
      - "80:8000"
    volumes:
      - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
    networks:
      - jupyterhub_network

networks:
  jupyterhub_network:
    external:
      name: "jupyterhub_network"
